(deftheme purezen
  "peace, zen and love, I love emacs since 2024-10-01")

(custom-theme-set-faces
 'purezen
 '(ansi-color-bright-cyan ((t (:background "blue" :foreground "blue"))))
 '(ansi-color-bright-green ((t (:background "sea green" :foreground "sea green"))))
 '(ansi-color-bright-yellow ((t (:background "saddle brown" :foreground "saddle brown"))))
 '(ansi-color-cyan ((t (:background "medium blue" :foreground "medium blue"))))
 '(ansi-color-green ((t (:background "green" :foreground "green"))))
 '(ansi-color-underline ((t nil)))
 '(ansi-color-yellow ((t (:background "red" :foreground "red"))))
 '(avy-lead-face ((t (:background "#000000" :foreground "#FFFFFF" :weight ultra-heavy))))
 '(avy-lead-face-0 ((t (:background "#000000" :foreground "#FFFFFF"))))
 '(avy-lead-face-1 ((t (:background "#000000" :foreground "#FFFFFF"))))
 '(avy-lead-face-2 ((t (:background "#000000" :foreground "#FFFFFF"))))
 '(bold ((t (:inherit (default)))))
 '(bookmark-face ((t (:distant-foreground "#000000" :foreground "#000000"))))
 '(button ((t (:foreground "#000000" :underline t))))
 '(compilation-error ((t nil)))
 '(compilation-info ((t (:foreground "#000000" :slant normal :weight regular))))
 '(compilation-mode-line-exit ((t (:weight regular :foreground "#000000" :inherit compilation-info))))
 '(compilation-mode-line-fail ((t (:inherit compilation-error :foreground "#000000" :weight normal))))
 '(compilation-mode-line-run ((t (:inherit compilation-warning :foreground "#000000" :weight regular))))
 '(compilation-warning ((t (:inherit default))))
 '(completions-common-part ((t (:background "#FFFFFF" :foreground "#000000" :weight bold))))
 '(completions-highlight ((t (:inherit highlight :weight bold))))
 '(consult-separator ((t (:foreground "#FFFFFF"))))
 '(corfu-annotations ((t nil)))
 '(corfu-bar ((t (:background "#000000"))))
 '(corfu-border ((t (:background "#000000"))))
 '(corfu-current ((t (:extend t :background "#FFFFFF" :foreground "#000000" :strike-through t :weight bold))))
 '(corfu-default ((t (:background "#FFFFFF"))))
 '(cursor ((t (:background "#000000" :foreground "#FFFFFF" :weight normal))))
 '(custom-button ((t (:background "#FFFFFF" :foreground "#000000" :box (:line-width (2 . 2) :style released-button)))))
 '(custom-button-mouse ((t (:background "#FFFFFF" :foreground "#000000" :box (:line-width (2 . 2) :style released-button)))))
 '(custom-button-pressed ((t (:background "#FFFFFF" :foreground "#000000" :box (:line-width (2 . 2) :style pressed-button)))))
 '(custom-changed ((t (:background "#000000" :foreground "#FFFFFF"))))
 '(custom-comment ((t (:background "#FFFFFF"))))
 '(custom-link ((t (:inherit (link)))))
 '(custom-rogue ((t (:background "#000000" :foreground "#FFFFFF"))))
 '(custom-set ((((min-colors 88) (class color)) (:background "#FFFFFF" :foreground "blue1")) (((class color)) (:background "#FFFFFF" :foreground "blue")) (t (:slant italic))))
 '(custom-state ((t (:foreground "#000000"))))
 '(dictionary-button-face ((t (:weight bold))))
 '(dictionary-reference-face ((((type x) (class color) (background dark)) (:foreground "yellow")) (((type tty) (class color) (background dark)) (:foreground "cyan")) (((class color) (background light)) (:foreground "blue")) (t (:underline (:color foreground-color :style line :position nil)))))
 '(dictionary-word-definition-face ((t (:family "Bookerly"))))
 '(dictionary-word-entry-face ((t (:foreground "#FFFFFF" :height 0.1 :width condensed))))
 '(diff-error ((t (:background "#000000" :foreground "#FFFFFF" :underline (:color "#FFFFFF" :style wave :position nil) :weight bold))))
 '(diff-file-header ((t (:extend t :background "#FFFFFF" :weight bold))))
 '(diff-function ((t (:inherit (diff-header)))))
 '(diff-header ((t (:extend t :background "#FFFFFF" :weight semi-bold))))
 '(diff-index ((t (:inherit diff-file-header))))
 '(diff-refine-added ((t (:background "#FFFFFF" :foreground "#000000" :weight bold))))
 '(diff-refine-removed ((t (:background "#FFFFFF" :foreground "#000000" :strike-through t))))
 '(diff-removed ((t (:inherit diff-changed :strike-through t))))
 '(dired-async-failures ((t (:background "#FFFFFF" :foreground "#000000" :inherit error))))
 '(dired-async-message ((t (:inherit success :foreground "#000000" :background "#FFFFFF"))))
 '(dired-async-mode-message ((t (:inherit warning :foreground "#000000" :background "#FFFFFF"))))
 '(dired-broken-symlink ((t (:background "#000000" :foreground "#FFFFFF" :weight bold))))
 '(dired-mark ((t (:foreground "#000000" :background "#FFFFFF" :inverse-video t))))
 '(dired-marked ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(diredfl-compressed-file-name ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(diredfl-compressed-file-suffix ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(diredfl-date-time ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(diredfl-deletion ((t (:inherit error :foreground "#000000" :background "#FFFFFF" :inverse-video t))))
 '(diredfl-deletion-file-name ((t (:inherit error :foreground "#000000" :background "#FFFFFF"))))
 '(diredfl-dir-heading ((t (:foreground "#000000" :background "#FFFFFF" :weight bold))))
 '(diredfl-dir-name ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(diredfl-dir-priv ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(diredfl-exec-priv ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(diredfl-executable-tag ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(diredfl-file-name ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(diredfl-file-suffix ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(diredfl-flag-mark ((t (:foreground "#000000" :background "#FFFFFF" :inverse-video t))))
 '(diredfl-flag-mark-line ((t (:background "#FFFFFF" :inherit highlight))))
 '(diredfl-ignored-file-name ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(diredfl-link-priv ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(diredfl-mode-line-flagged ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(diredfl-mode-line-marked ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(diredfl-no-priv ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(diredfl-number ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(diredfl-other-priv ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(diredfl-rare-priv ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(diredfl-read-priv ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(diredfl-symlink ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(diredfl-write-priv ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(eglot-highlight-symbol-face ((t (:weight normal))))
 '(envrc-mode-line-error-face ((t nil)))
 '(envrc-mode-line-none-face ((t (:weight regular :foreground "#000000"))))
 '(envrc-mode-line-on-face ((t nil)))
 '(epa-mark ((t (:foreground "#000000" :box (:line-width (1 . 1) :color "#000000" :style pressed-button) :weight bold))))
 '(error ((t (:foreground "#000000" :underline (:color foreground-color :style wave :position nil) :weight regular))))
 '(escape-glyph ((t (:foreground "#000000"))))
 '(eww-form-checkbox ((t (:background "#FFFFFF" :foreground "#000000" :box (:line-width (2 . 2) :style released-button)))))
 '(eww-form-file ((t (:background "#FFFFFF" :foreground "#000000" :box (:line-width (2 . 2) :style released-button)))))
 '(eww-form-select ((t (:background "#FFFFFF" :foreground "#000000" :box (:line-width (2 . 2) :style released-button)))))
 '(eww-form-submit ((t (:background "#FFFFFF" :foreground "#000000" :box (:line-width (2 . 2) :style released-button)))))
 '(eww-form-text ((t (:background "#FFFFFF" :foreground "#000000" :box (1 . 1)))))
 '(eww-form-textarea ((t (:background "#FFFFFF" :foreground "#000000" :box (1 . 1)))))
 '(eww-valid-certificate ((t (:foreground "#000000" :weight bold))))
 '(fixed-pitch ((t (:weight normal :family "Bookerly"))))
 '(fixed-pitch-serif ((t (:family "Bookerly"))))
 '(flymake-error ((t nil)))
 '(flymake-note ((t nil)))
 '(flymake-warning ((t nil)))
 '(font-lock-bracket-face ((t (:inherit font-lock-punctuation-face))))
 '(font-lock-builtin-face ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#000000"))))
 '(font-lock-comment-face ((t nil)))
 '(font-lock-constant-face ((t nil)))
 '(font-lock-delimiter-face ((t (:inherit font-lock-punctuation-face))))
 '(font-lock-doc-face ((t (:foreground "#000000" :weight regular))))
 '(font-lock-doc-markup-face ((t (:inherit font-lock-constant-face))))
 '(font-lock-escape-face ((t nil)))
 '(font-lock-function-call-face ((t (:inherit font-lock-function-name-face))))
 '(font-lock-function-name-face ((t (:foreground "#000000"))))
 '(font-lock-keyword-face ((t (:foreground "#000000"))))
 '(font-lock-misc-punctuation-face ((t (:inherit font-lock-punctuation-face))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-number-face ((t nil)))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#000000"))))
 '(font-lock-property-name-face ((t (:inherit font-lock-variable-name-face))))
 '(font-lock-property-use-face ((t (:inherit font-lock-property-name-face))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t nil)))
 '(font-lock-regexp-grouping-construct ((t nil)))
 '(font-lock-string-face ((t (:foreground "#000000"))))
 '(font-lock-type-face ((t (:foreground "#000000"))))
 '(font-lock-variable-name-face ((t (:foreground "#000000" :underline nil))))
 '(font-lock-variable-use-face ((t (:inherit font-lock-variable-name-face))))
 '(font-lock-warning-face ((t (:foreground "#000000" :weight regular))))
 '(fringe ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(gnus-header-from ((t (:inherit gnus-header :foreground "#000000"))))
 '(header-line ((t (:inherit mode-line :background "#FFFFFF" :foreground "#000000" :box nil))))
 '(help-key-binding ((t (:inherit fixed-pitch :background "#FFFFFF" :foreground "DarkBlue" :box (:line-width (-1 . -1) :color "grey80")))))
 '(hexl-ascii-region ((t (:background "#FFFFFF" :foreground "#000000" :box nil))))
 '(highlight ((t (:weight bold))))
 '(homoglyph ((t (:foreground "#000000"))))
 '(icon-button ((t (:box (:line-width (3 . -1) :color "#000000" :style flat-button) :foreground "#000000" :background "#FFFFFF" :inherit icon))))
 '(info-header-node ((t (:inherit info-node))))
 '(info-node ((t (:foreground "#000000" :slant normal :weight normal))))
 '(isearch ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(isearch-fail ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(lazy-highlight ((t (:background "#FFFFFF" :distant-foreground "#000000" :weight semi-bold))))
 '(link ((t (:foreground "#000000"))))
 '(link-visited ((t (:inherit link :foreground "#000000"))))
 '(magit-bisect-bad ((t (:foreground "#000000" :slant italic))))
 '(magit-bisect-good ((t (:foreground "#000000" :weight bold))))
 '(magit-bisect-skip ((t (:foreground "#000000"))))
 '(magit-blame-heading ((t (:foreground "#000000" :background "#FFFFFF" :box 1))))
 '(magit-blame-highlight ((t (:extend t :background "#FFFFFF" :foreground "#000000"))))
 '(magit-blame-margin ((t (:inherit magit-blame-highlight :underline (:color foreground-color :style dashes :position nil) :slant normal :weight normal))))
 '(magit-branch-current ((t (:weight bold :inherit magit-branch-local))))
 '(magit-branch-local ((t (:foreground "#000000" :slant italic :weight bold))))
 '(magit-branch-remote ((t (:foreground "#000000" :weight bold))))
 '(magit-cherry-equivalent ((t (:foreground "#000000"))))
 '(magit-cherry-unmatched ((t (:foreground "#000000" :italic t))))
 '(magit-diff-added ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(magit-diff-added-highlight ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(magit-diff-base ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(magit-diff-base-highlight ((t (:background "#FFFFFF" :foreground "#000000" :slant italic))))
 '(magit-diff-context ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(magit-diff-context-highlight ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(magit-diff-file-heading-selection ((t (:inherit magit-diff-file-heading-highlight :extend t :foreground "#000000"))))
 '(magit-diff-hunk-heading ((t (:background "#FFFFFF" :foreground "#000000" :weight bold))))
 '(magit-diff-hunk-heading-highlight ((t (:background "#FFFFFF" :foreground "#000000" :weight bold))))
 '(magit-diff-hunk-heading-selection ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(magit-diff-lines-heading ((t (:background "#FFFFFF" :foreground "#000000" :box 1))))
 '(magit-diff-refine-added ((t (:background "#FFFFFF" :foreground "#000000" :weight bold))))
 '(magit-diff-refine-removed ((t (:background "#FFFFFF" :foreground "#000000" :strike-through t))))
 '(magit-diff-removed ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(magit-diff-removed-highlight ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(magit-diffstat-added ((t (:foreground "#000000" :weight bold))))
 '(magit-diffstat-removed ((t (:foreground "#000000"))))
 '(magit-dimmed ((t (:foreground "#000000"))))
 '(magit-hash ((t (:foreground "#000000" :slant italic))))
 '(magit-log-author ((t (:foreground "#000000" :weight bold))))
 '(magit-log-date ((t (:foreground "#000000"))))
 '(magit-log-graph ((t (:foreground "#000000"))))
 '(magit-process-ng ((t (:foreground "#000000" :weight bold :box 1))))
 '(magit-process-ok ((t (:foreground "#000000" :weight bold :box 1))))
 '(magit-reflog-amend ((t (:foreground "#000000" :slant italic))))
 '(magit-reflog-checkout ((t (:foreground "#000000" :weight bold))))
 '(magit-reflog-cherry-pick ((t (:foreground "#000000"))))
 '(magit-reflog-commit ((t (:foreground "#000000" :weight bold))))
 '(magit-reflog-merge ((t (:foreground "#000000" :slant italic))))
 '(magit-reflog-other ((t (:foreground "#000000"))))
 '(magit-reflog-rebase ((t (:foreground "#000000" :slant italic))))
 '(magit-reflog-remote ((t (:foreground "#000000" :weight bold))))
 '(magit-reflog-reset ((t (:foreground "#000000"))))
 '(magit-refname ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(magit-section-heading ((t (:foreground "#000000" :weight bold :height 1.2))))
 '(magit-section-heading-selection ((t (:foreground "#000000"))))
 '(magit-section-highlight ((t (:background "#FFFFFF"))))
 '(magit-sequence-drop ((t (:foreground "#000000" :slant italic))))
 '(magit-sequence-head ((t (:foreground "#000000" :weight bold))))
 '(magit-sequence-part ((t (:foreground "#000000" :italic t))))
 '(magit-sequence-stop ((t (:foreground "#000000" :box 1))))
 '(magit-signature-bad ((t (:foreground "#000000" :weight bold :slant italic))))
 '(magit-signature-error ((t (:foreground "#000000"))))
 '(magit-signature-expired ((t (:foreground "#000000"))))
 '(magit-signature-good ((t (:foreground "#000000" :weight bold))))
 '(magit-signature-revoked ((t (:foreground "#000000" :slant italic))))
 '(magit-signature-untrusted ((t (:foreground "#000000"))))
 '(magit-tag ((t (:foreground "#000000" :weight bold :box 1))))
 '(marginalia-documentation ((t nil)))
 '(markdown-highlighting-face ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(match ((t (:background "#FFFFFF" :foreground "#000000" :weight bold))))
 '(message-header-name ((t (:foreground "#000000"))))
 '(message-header-other ((t (:foreground "#000000"))))
 '(message-header-to ((t (:foreground "#000000" :weight bold))))
 '(message-mml ((t (:foreground "#000000"))))
 '(minibuffer-nonselected ((t (:background "#FFFFFF" :foreground "#000000" :weight bold))))
 '(minibuffer-prompt ((t (:foreground "#000000" :weight regular))))
 '(mode-line ((t (:background "#FFFFFF" :foreground "#000000" :height 1.0))))
 '(mode-line-buffer-id ((t (:weight regular))))
 '(mode-line-emphasis ((t (:weight regular))))
 '(mode-line-highlight ((t nil)))
 '(mode-line-inactive ((t (:height 1.0))))
 '(next-error ((t (:background "#FFFFFF" :distant-foreground "#000000" :foreground "#000000" :weight semi-bold))))
 '(orderless-match-face-0 ((t (:foreground "#000000" :weight bold))))
 '(orderless-match-face-1 ((t (:foreground "#000000" :weight bold))))
 '(orderless-match-face-2 ((t (:foreground "#000000" :weight bold))))
 '(orderless-match-face-3 ((t (:foreground "#000000" :weight bold))))
 '(org-agenda-structure ((t (:foreground "#000000"))))
 '(org-clock-overlay ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(org-column ((t (:background "#FFFFFF" :strike-through nil :underline nil :slant normal :weight normal))))
 '(org-column-title ((t (:background "#FFFFFF" :weight bold))))
 '(org-dispatcher-highlight ((t (:background "#000000" :foreground "#FFFFFF" :weight bold))))
 '(org-headline-done ((t (:foreground "#000000"))))
 '(org-headline-todo ((t (:foreground "#000000"))))
 '(org-mode-line-clock-overrun ((t (:inherit mode-line :background "#FFFFFF"))))
 '(org-scheduled-previously ((t (:foreground "#000000"))))
 '(org-scheduled-today ((t (:foreground "#000000"))))
 '(org-table-header ((t (:inherit org-table :background "#FFFFFF" :foreground "#000000"))))
 '(package-mark-delete-line ((t (:extend t :background "#FFFFFF" :strike-through t))))
 '(package-mark-install-line ((t (:extend t :background "#FFFFFF" :underline t))))
 '(pdf-links-read-link ((t (:background "#000000" :foreground "#FFFFFF"))))
 '(pyim-page ((t (:inherit default :background "#000000" :foreground "#FFFFFF"))))
 '(pyim-page-border ((t (:background "#000000" :foreground "#FFFFFF"))))
 '(pyim-page-selection ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(pyim-preview-face ((t (:underline (:color foreground-color :style line :position nil)))))
 '(query-replace ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(region ((t (:extend t :background "#FFFFFF" :foreground "#000000" :strike-through t))))
 '(secondary-selection ((t (:extend t :background "#FFFFFF" :strike-through t :weight normal))))
 '(shadow ((t (:foreground "#000000"))))
 '(show-paren-match ((t (:background "#FFFFFF" :distant-foreground "#000000" :foreground "#000000" :weight bold))))
 '(show-paren-match-expression ((t (:inherit show-paren-match))))
 '(show-paren-mismatch ((t (:background "#FFFFFF" :foreground "#000000" :underline t))))
 '(shr-abbreviation ((t (:inherit (default)))))
 '(shr-code ((t (:inherit (default)))))
 '(shr-h1 ((t (:inherit (default)))))
 '(shr-h2 ((t (:inherit (default)))))
 '(shr-h3 ((t (:inherit (default)))))
 '(shr-h4 ((t (:inherit (default)))))
 '(shr-h5 ((t (:inherit (default)))))
 '(shr-h6 ((t (:inherit (default)))))
 '(shr-link ((t (:inherit (default)))))
 '(shr-mark ((t (:inherit (default)))))
 '(shr-selected-link ((t (:inherit (default)))))
 '(shr-sliced-image ((t (:inherit (default)))))
 '(shr-strike-through ((t (:inherit (default)))))
 '(shr-sup ((t (:inherit (default)))))
 '(shr-text ((t (:inherit (default)))))
 '(success ((t (:foreground "#000000" :underline t :weight bold))))
 '(tab-bar ((t (:inherit variable-pitch :background "#FFFFFF" :foreground "#000000"))))
 '(tab-bar-tab-highlight ((t (:background "#FFFFFF" :foreground "#000000" :box (:line-width (1 . 1) :style released-button)))))
 '(tab-bar-tab-inactive ((t (:background "#000000" :foreground "#FFFFFF"))))
 '(tab-bar-tab-ungrouped ((t (:inherit (shadow tab-bar-tab-inactive)))))
 '(tab-line ((t (:inherit variable-pitch :background "#FFFFFF" :foreground "#000000" :height 0.9))))
 '(tab-line-highlight ((t (:background "#FFFFFF" :foreground "#000000" :box (:line-width (1 . 1) :style released-button)))))
 '(tldr-code-block ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(tldr-command-argument ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(tldr-command-itself ((t (:background "#FFFFFF" :foreground "#000000" :weight normal))))
 '(tldr-description ((t (:foreground "#000000"))))
 '(tldr-introduction ((t (:foreground "#000000" :slant normal))))
 '(tldr-title ((t (:foreground "#FFFFFF" :height 0.1))))
 '(tool-bar ((t (:background "#FFFFFF" :foreground "#000000" :box (:line-width (1 . 1) :style released-button)))))
 '(tooltip ((t (:foreground "#000000" :background "#FFFFFF" :inherit variable-pitch))))
 '(trailing-whitespace ((t (:background "#000000"))))
 '(transient-argument ((t (:foreground "#000000" :bold t))))
 '(transient-disabled-suffix ((t (:background "#FFFFFF"))))
 '(transient-enabled-suffix ((t (:background "#FFFFFF" :weight bold))))
 '(transient-heading ((t (:foreground "#000000"))))
 '(transient-key ((t (:foreground "#000000"))))
 '(transient-key-exit ((t (:foreground "#000000"))))
 '(transient-key-noop ((t (:foreground "#000000"))))
 '(transient-key-recurse ((t (:foreground "#000000"))))
 '(transient-key-return ((t (:foreground "#000000"))))
 '(transient-key-stack ((t (:foreground "#000000"))))
 '(transient-key-stack ((t (:inherit transient-key :foreground "#000000"))))
 '(transient-key-stay ((t (:foreground "#000000"))))
 '(transient-mismatched-key ((t (:foreground "#000000" :underline t))))
 '(transient-nonstandard-key ((t (:foreground "#000000" :underline t))))
 '(transient-pink ((t (:foreground "#000000" :bold t))))
 '(transient-purple ((t (:foreground "#000000" :bold t))))
 '(transient-red ((t (:foreground "#000000" :bold t))))
 '(transient-teal ((t (:foreground "#000000" :bold t))))
 '(transient-unreachable ((t (:foreground "#000000"))))
 '(transient-unreachable-key ((t (:foreground "#000000"))))
 '(transient-value ((t (:foreground "#000000"))))
 '(transient-value ((t (:foreground "#000000"))))
 '(variable-pitch ((t (:inherit default))))
 '(vertico-current ((t (:weight bold :extend t :inherit highlight))))
 '(warning ((t (:foreground "#000000" :underline (:color foreground-color :style wave :position nil) :weight normal))))
 '(wgrep-delete-face ((t (:background "#000000" :foreground "#FFFFFF" :strike-through t))))
 '(wgrep-done-face ((t (:foreground "#000000"))))
 '(wgrep-face ((t (:background "#000000" :foreground "#FFFFFF"))))
 '(wgrep-file-face ((t (:background "#000000" :foreground "#FFFFFF"))))
 '(wgrep-reject-face ((t (:foreground "#000000" :underline (:color foreground-color :style wave :position nil) :weight bold))))
 '(widget-field ((t (:box (:line-width (1 . -1) :color "#000000") :background "#FFFFFF" :extend t))))
 '(window-divider ((t (:foreground "#000000"))))
 '(window-divider-first-pixel ((t (:foreground "#FFFFFF"))))
 '(no-emoji ((t (:foreground "#FFFFFF" :height 0.1))))
 '(info-title-1 ((t nil)))
 '(info-title-2 ((t nil)))
 '(info-title-3 ((t nil)))
 '(info-title-4 ((t (:inherit variable-pitch))))
 '(info-menu-header ((t (:inherit variable-pitch))))
 '(info-index-match ((t nil)))
 '(info-xref-visited ((t nil)))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#FFFFFF" :foreground "#000000" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight regular :height 160 :width normal :foundry "DAMA" :family "Bookerly")))))

(provide-theme 'purezen)
